/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_CHATGPT
#define VCZH_WORKFLOW_COMPILER_GENERATED_CHATGPT

#include "GacfredPartialClasses.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace gacfred
{
	class ChatGPT : public ::vl::presentation::controls::GuiCustomControl, public ::gacfred::ChatGPTConstructor, public ::vl::reflection::Description<ChatGPT>
	{
		friend class ::gacfred::ChatGPTConstructor;
		friend struct ::vl_workflow_global::__vwsnf21_Gacfred_gacfred_ChatGPTConstructor___vwsn_gacfred_ChatGPT_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf22_Gacfred_gacfred_ChatGPTConstructor___vwsn_gacfred_ChatGPT_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf23_Gacfred_gacfred_ChatGPTConstructor___vwsn_gacfred_ChatGPT_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<ChatGPT>;
#endif
	public:
		::vl::vint64_t selected;
	private:
		void Paste();
	public:
		::vl::Ptr<::gacfred::IChatGPTViewModel> __vwsn_parameter_ViewModel;
		::vl::Ptr<::gacfred::IChatGPTViewModel> GetViewModel();
		ChatGPT(::vl::Ptr<::gacfred::IChatGPTViewModel> __vwsn_ctor_parameter_ViewModel);
		void __vwsn_instance_ctor_();
		~ChatGPT();

	/* USER_CONTENT_BEGIN(custom members of ::gacfred::ChatGPT) */
	/* USER_CONTENT_END() */
	};

}
#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
