/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "Gacfred.h"
/* CodePack:BeginIgnore() */
#ifndef VCZH_DEBUG_NO_REFLECTION
/* CodePack:ConditionOff(VCZH_DEBUG_NO_REFLECTION, GacfredReflection.h) */
#include "GacfredReflection.h"
#endif
/* CodePack:EndIgnore() */

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

#define GLOBAL_SYMBOL ::vl_workflow_global::Gacfred::
#define GLOBAL_NAME ::vl_workflow_global::Gacfred::Instance().
#define GLOBAL_OBJ &::vl_workflow_global::Gacfred::Instance()

/* USER_CONTENT_BEGIN(custom global declarations) */
/* USER_CONTENT_END() */

/***********************************************************************
Class (::gacfred::Clipboard)
***********************************************************************/

namespace gacfred
{
	void Clipboard::InstallClipboard()
	{/* USER_CONTENT_BEGIN(::gacfred::Clipboard) */
        this->listViewCopies->SetSelected(0, true);
        this->listViewCopies->SetArranger(vl::Ptr(new vl::presentation::controls::list::FreeHeightItemArranger()));
	}/* USER_CONTENT_END() */

	void Clipboard::Paste()
	{/* USER_CONTENT_BEGIN(::gacfred::Clipboard) */
	}/* USER_CONTENT_END() */

	::vl::Ptr<::vl::presentation::controls::IGuiAnimation> Clipboard::PerformChangeAnimation(::vl::presentation::compositions::GuiBoundsComposition* backgroundBar, ::vl::vint64_t posX)
	{
		return ::vl::presentation::controls::IGuiAnimationCoroutine::Create(vl::Func(::vl_workflow_global::__vwsnf32_Gacfred_gacfred_Clipboard_PerformChangeAnimation_(backgroundBar, posX, this)));
	}

	::vl::Ptr<::gacfred::IClipboardViewModel> Clipboard::GetViewModel()
	{
		return this->__vwsn_parameter_ViewModel;
	}

	Clipboard::Clipboard(::vl::Ptr<::gacfred::IClipboardViewModel> __vwsn_ctor_parameter_ViewModel)
		: ::vl::presentation::controls::GuiCustomControl(::vl::presentation::theme::ThemeName::CustomControl)
		, selected((- static_cast<::vl::vint64_t>(1L)))
		, lastPosX(static_cast<::vl::vint64_t>(0L))
		, bezier(GLOBAL_NAME CubicBezier(static_cast<double>(0.25), static_cast<double>(static_cast<::vl::vint64_t>(0L)), static_cast<double>(static_cast<::vl::vint64_t>(0L)), static_cast<double>(static_cast<::vl::vint64_t>(1L))))
		, anim(::vl::Ptr<::vl::presentation::controls::IGuiAnimation>())
		, __vwsn_parameter_ViewModel(::vl::Ptr<::gacfred::IClipboardViewModel>())
	{
		(this->__vwsn_parameter_ViewModel = __vwsn_ctor_parameter_ViewModel);
		auto __vwsn_resource_ = ::vl::__vwsn::This(::vl::presentation::GetResourceManager())->GetResourceFromClassName(::vl::WString::Unmanaged(L"gacfred::Clipboard"));
		auto __vwsn_resolver_ = ::vl::Ptr<::vl::presentation::GuiResourcePathResolver>(new ::vl::presentation::GuiResourcePathResolver(__vwsn_resource_, ::vl::__vwsn::This(__vwsn_resource_.Obj())->GetWorkingDirectory()));
		::vl::__vwsn::This(this)->SetResourceResolver(__vwsn_resolver_);
		::vl::__vwsn::This(this)->__vwsn_gacfred_Clipboard_Initialize(this);
		this->__vwsn_instance_ctor_();
	}

	void Clipboard::__vwsn_instance_ctor_()
	{
		(::vl::__vwsn::This(this->GetViewModel().Obj())->ListView = static_cast<::vl::presentation::controls::GuiListControl*>(this->listViewCopies));
		::vl::__vwsn::This(this->self)->InstallClipboard();
	}

	Clipboard::~Clipboard()
	{
		this->FinalizeInstanceRecursively(static_cast<::vl::presentation::controls::GuiCustomControl*>(this));
	}

}
#undef GLOBAL_SYMBOL
#undef GLOBAL_NAME
#undef GLOBAL_OBJ

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
