/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "GacfredReflection.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			IMPL_CPP_TYPE_INFO(gacfred::Clipboard)
			IMPL_CPP_TYPE_INFO(gacfred::ClipboardConstructor)
			IMPL_CPP_TYPE_INFO(gacfred::CopyItemTemplate)
			IMPL_CPP_TYPE_INFO(gacfred::CopyItemTemplateConstructor)
			IMPL_CPP_TYPE_INFO(gacfred::CopyType)
			IMPL_CPP_TYPE_INFO(gacfred::DocumentLabelTemplate)
			IMPL_CPP_TYPE_INFO(gacfred::DocumentLabelTemplateConstructor)
			IMPL_CPP_TYPE_INFO(gacfred::IClipboardViewModel)
			IMPL_CPP_TYPE_INFO(gacfred::ICopy)
			IMPL_CPP_TYPE_INFO(gacfred::IMainWindowViewModel)
			IMPL_CPP_TYPE_INFO(gacfred::IProgramViewModel)
			IMPL_CPP_TYPE_INFO(gacfred::ItemBackgroundTemplate)
			IMPL_CPP_TYPE_INFO(gacfred::ItemBackgroundTemplateConstructor)
			IMPL_CPP_TYPE_INFO(gacfred::ListViewTemplate)
			IMPL_CPP_TYPE_INFO(gacfred::ListViewTemplateConstructor)
			IMPL_CPP_TYPE_INFO(gacfred::MainWindow)
			IMPL_CPP_TYPE_INFO(gacfred::MainWindowConstructor)
			IMPL_CPP_TYPE_INFO(gacfred::TransparentButtonTemplate)
			IMPL_CPP_TYPE_INFO(gacfred::TransparentButtonTemplateConstructor)
			IMPL_CPP_TYPE_INFO(gacfred::VScrollHandleTemplate)
			IMPL_CPP_TYPE_INFO(gacfred::VScrollHandleTemplateConstructor)
			IMPL_CPP_TYPE_INFO(gacfred::VScrollTemplate)
			IMPL_CPP_TYPE_INFO(gacfred::VScrollTemplateConstructor)
			IMPL_CPP_TYPE_INFO(gacfred::WindowTemplate)
			IMPL_CPP_TYPE_INFO(gacfred::WindowTemplateConstructor)

#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
#define _ ,
			BEGIN_CLASS_MEMBER(::gacfred::Clipboard)
				CLASS_MEMBER_BASE(::vl::presentation::controls::GuiCustomControl)
				CLASS_MEMBER_BASE(::gacfred::ClipboardConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::gacfred::Clipboard*(::vl::Ptr<::gacfred::IClipboardViewModel>), { L"__vwsn_ctor_parameter_ViewModel" })
				CLASS_MEMBER_METHOD(__vwsn_instance_ctor_, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetViewModel, NO_PARAMETER)
				CLASS_MEMBER_METHOD(InstallClipboard, NO_PARAMETER)
				CLASS_MEMBER_METHOD(Paste, NO_PARAMETER)
				CLASS_MEMBER_METHOD(PerformChangeAnimation, { L"backgroundBar" _ L"posX" })
				CLASS_MEMBER_FIELD(__vwsn_parameter_ViewModel)
				CLASS_MEMBER_PROPERTY_READONLY(ViewModel, GetViewModel)
				CLASS_MEMBER_FIELD(anim)
				CLASS_MEMBER_FIELD(bezier)
				CLASS_MEMBER_FIELD(lastPosX)
				CLASS_MEMBER_FIELD(selected)
			END_CLASS_MEMBER(::gacfred::Clipboard)

			BEGIN_CLASS_MEMBER(::gacfred::ClipboardConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::gacfred::ClipboardConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_gacfred_Clipboard_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(__vwsn_precompile_10)
				CLASS_MEMBER_FIELD(__vwsn_precompile_11)
				CLASS_MEMBER_FIELD(__vwsn_precompile_12)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				CLASS_MEMBER_FIELD(__vwsn_precompile_3)
				CLASS_MEMBER_FIELD(__vwsn_precompile_4)
				CLASS_MEMBER_FIELD(__vwsn_precompile_5)
				CLASS_MEMBER_FIELD(__vwsn_precompile_6)
				CLASS_MEMBER_FIELD(__vwsn_precompile_7)
				CLASS_MEMBER_FIELD(__vwsn_precompile_8)
				CLASS_MEMBER_FIELD(__vwsn_precompile_9)
				CLASS_MEMBER_FIELD(ViewModel)
				CLASS_MEMBER_FIELD(btn1)
				CLASS_MEMBER_FIELD(btn2)
				CLASS_MEMBER_FIELD(btn3)
				CLASS_MEMBER_FIELD(buttonMA)
				CLASS_MEMBER_FIELD(containerMA)
				CLASS_MEMBER_FIELD(listViewCopies)
				CLASS_MEMBER_FIELD(self)
			END_CLASS_MEMBER(::gacfred::ClipboardConstructor)

			BEGIN_CLASS_MEMBER(::gacfred::CopyItemTemplate)
				CLASS_MEMBER_BASE(::vl::presentation::templates::GuiListItemTemplate)
				CLASS_MEMBER_BASE(::gacfred::CopyItemTemplateConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::gacfred::CopyItemTemplate*(::vl::Ptr<::gacfred::ICopy>), { L"__vwsn_ctor_parameter_ViewModel" })
				CLASS_MEMBER_METHOD(GetViewModel, NO_PARAMETER)
				CLASS_MEMBER_FIELD(__vwsn_parameter_ViewModel)
				CLASS_MEMBER_PROPERTY_READONLY(ViewModel, GetViewModel)
			END_CLASS_MEMBER(::gacfred::CopyItemTemplate)

			BEGIN_CLASS_MEMBER(::gacfred::CopyItemTemplateConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::gacfred::CopyItemTemplateConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_gacfred_CopyItemTemplate_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(__vwsn_precompile_10)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				CLASS_MEMBER_FIELD(__vwsn_precompile_3)
				CLASS_MEMBER_FIELD(__vwsn_precompile_4)
				CLASS_MEMBER_FIELD(__vwsn_precompile_5)
				CLASS_MEMBER_FIELD(__vwsn_precompile_6)
				CLASS_MEMBER_FIELD(__vwsn_precompile_7)
				CLASS_MEMBER_FIELD(__vwsn_precompile_8)
				CLASS_MEMBER_FIELD(__vwsn_precompile_9)
				CLASS_MEMBER_FIELD(ViewModel)
				CLASS_MEMBER_FIELD(self)
			END_CLASS_MEMBER(::gacfred::CopyItemTemplateConstructor)

			BEGIN_ENUM_ITEM_MERGABLE(::gacfred::CopyType)
				ENUM_CLASS_ITEM(Image)
				ENUM_CLASS_ITEM(None)
				ENUM_CLASS_ITEM(Text)
			END_ENUM_ITEM(::gacfred::CopyType)

			BEGIN_CLASS_MEMBER(::gacfred::DocumentLabelTemplate)
				CLASS_MEMBER_BASE(::vl::presentation::templates::GuiDocumentLabelTemplate)
				CLASS_MEMBER_BASE(::gacfred::DocumentLabelTemplateConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::gacfred::DocumentLabelTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(::gacfred::DocumentLabelTemplate)

			BEGIN_CLASS_MEMBER(::gacfred::DocumentLabelTemplateConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::gacfred::DocumentLabelTemplateConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_gacfred_DocumentLabelTemplate_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(self)
			END_CLASS_MEMBER(::gacfred::DocumentLabelTemplateConstructor)

			BEGIN_INTERFACE_MEMBER(::gacfred::IClipboardViewModel)
				CLASS_MEMBER_BASE(::gacfred::IProgramViewModel)
				CLASS_MEMBER_METHOD(AddCopy, { L"copy" })
				CLASS_MEMBER_METHOD(GetCopies, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetCopy, { L"idx" })
				CLASS_MEMBER_METHOD(GetShowType, NO_PARAMETER)
				CLASS_MEMBER_METHOD(SetShowType, { L"__vwsn_value_" })
				CLASS_MEMBER_EVENT(ShowTypeChanged)
				CLASS_MEMBER_PROPERTY_READONLY(Copies, GetCopies)
				CLASS_MEMBER_FIELD(ListView)
				CLASS_MEMBER_PROPERTY_EVENT(ShowType, GetShowType, SetShowType, ShowTypeChanged)
			END_INTERFACE_MEMBER(::gacfred::IClipboardViewModel)

			BEGIN_INTERFACE_MEMBER(::gacfred::ICopy)
				CLASS_MEMBER_BASE(::vl::reflection::IDescriptable)
				CLASS_MEMBER_METHOD(GetContent, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetCtime, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetIdx, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetRichContent, { L"full" })
				CLASS_MEMBER_METHOD(GetSeparatorVisible, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetShowtime, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetType, NO_PARAMETER)
				CLASS_MEMBER_METHOD(SetContent, { L"__vwsn_value_" })
				CLASS_MEMBER_METHOD(SetCtime, { L"__vwsn_value_" })
				CLASS_MEMBER_METHOD(SetIdx, { L"__vwsn_value_" })
				CLASS_MEMBER_METHOD(SetSeparatorVisible, { L"__vwsn_value_" })
				CLASS_MEMBER_METHOD(SetType, { L"__vwsn_value_" })
				CLASS_MEMBER_EVENT(SeparatorVisibleChanged)
				CLASS_MEMBER_PROPERTY(Content, GetContent, SetContent)
				CLASS_MEMBER_PROPERTY(Ctime, GetCtime, SetCtime)
				CLASS_MEMBER_PROPERTY(Idx, GetIdx, SetIdx)
				CLASS_MEMBER_PROPERTY_EVENT(SeparatorVisible, GetSeparatorVisible, SetSeparatorVisible, SeparatorVisibleChanged)
				CLASS_MEMBER_PROPERTY_READONLY(Showtime, GetShowtime)
				CLASS_MEMBER_PROPERTY(Type, GetType, SetType)
			END_INTERFACE_MEMBER(::gacfred::ICopy)

			BEGIN_INTERFACE_MEMBER(::gacfred::IMainWindowViewModel)
				CLASS_MEMBER_BASE(::vl::reflection::IDescriptable)
				CLASS_MEMBER_METHOD(Copy, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetProgram, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetProgramViewModel, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetSearch, NO_PARAMETER)
				CLASS_MEMBER_METHOD(HandleKeyDown, { L"arguments" })
				CLASS_MEMBER_METHOD(ResetSearch, NO_PARAMETER)
				CLASS_MEMBER_METHOD(SetProgram, { L"__vwsn_value_" })
				CLASS_MEMBER_METHOD(SetProgramViewModel, { L"__vwsn_value_" })
				CLASS_MEMBER_METHOD(SetSearch, { L"__vwsn_value_" })
				CLASS_MEMBER_EVENT(ProgramChanged)
				CLASS_MEMBER_EVENT(SearchChanged)
				CLASS_MEMBER_PROPERTY_EVENT(Program, GetProgram, SetProgram, ProgramChanged)
				CLASS_MEMBER_FIELD(ProgramControl)
				CLASS_MEMBER_PROPERTY(ProgramViewModel, GetProgramViewModel, SetProgramViewModel)
				CLASS_MEMBER_PROPERTY_EVENT(Search, GetSearch, SetSearch, SearchChanged)
			END_INTERFACE_MEMBER(::gacfred::IMainWindowViewModel)

			BEGIN_INTERFACE_MEMBER(::gacfred::IProgramViewModel)
				CLASS_MEMBER_BASE(::vl::reflection::IDescriptable)
				CLASS_MEMBER_METHOD(GetSearch, NO_PARAMETER)
				CLASS_MEMBER_METHOD(HandleKeyDown, { L"arguments" })
				CLASS_MEMBER_METHOD(SetSearch, { L"__vwsn_value_" })
				CLASS_MEMBER_EVENT(SearchChanged)
				CLASS_MEMBER_PROPERTY_EVENT(Search, GetSearch, SetSearch, SearchChanged)
				CLASS_MEMBER_FIELD(mainWindowViewModel)
			END_INTERFACE_MEMBER(::gacfred::IProgramViewModel)

			BEGIN_CLASS_MEMBER(::gacfred::ItemBackgroundTemplate)
				CLASS_MEMBER_BASE(::vl::presentation::templates::GuiSelectableButtonTemplate)
				CLASS_MEMBER_BASE(::gacfred::ItemBackgroundTemplateConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::gacfred::ItemBackgroundTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(::gacfred::ItemBackgroundTemplate)

			BEGIN_CLASS_MEMBER(::gacfred::ItemBackgroundTemplateConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::gacfred::ItemBackgroundTemplateConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_gacfred_ItemBackgroundTemplate_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(self)
			END_CLASS_MEMBER(::gacfred::ItemBackgroundTemplateConstructor)

			BEGIN_CLASS_MEMBER(::gacfred::ListViewTemplate)
				CLASS_MEMBER_BASE(::vl::presentation::templates::GuiListViewTemplate)
				CLASS_MEMBER_BASE(::gacfred::ListViewTemplateConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::gacfred::ListViewTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(::gacfred::ListViewTemplate)

			BEGIN_CLASS_MEMBER(::gacfred::ListViewTemplateConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::gacfred::ListViewTemplateConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_gacfred_ListViewTemplate_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(look)
				CLASS_MEMBER_FIELD(self)
			END_CLASS_MEMBER(::gacfred::ListViewTemplateConstructor)

			BEGIN_CLASS_MEMBER(::gacfred::MainWindow)
				CLASS_MEMBER_BASE(::vl::presentation::controls::GuiWindow)
				CLASS_MEMBER_BASE(::gacfred::MainWindowConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::gacfred::MainWindow*(::vl::Ptr<::gacfred::IMainWindowViewModel>), { L"__vwsn_ctor_parameter_ViewModel" })
				CLASS_MEMBER_METHOD(__vwsn_instance_ctor_, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetViewModel, NO_PARAMETER)
				CLASS_MEMBER_FIELD(__vwsn_parameter_ViewModel)
				CLASS_MEMBER_PROPERTY_READONLY(ViewModel, GetViewModel)
			END_CLASS_MEMBER(::gacfred::MainWindow)

			BEGIN_CLASS_MEMBER(::gacfred::MainWindowConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::gacfred::MainWindowConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_gacfred_MainWindow_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(__vwsn_precompile_10)
				CLASS_MEMBER_FIELD(__vwsn_precompile_11)
				CLASS_MEMBER_FIELD(__vwsn_precompile_12)
				CLASS_MEMBER_FIELD(__vwsn_precompile_13)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				CLASS_MEMBER_FIELD(__vwsn_precompile_3)
				CLASS_MEMBER_FIELD(__vwsn_precompile_4)
				CLASS_MEMBER_FIELD(__vwsn_precompile_5)
				CLASS_MEMBER_FIELD(__vwsn_precompile_6)
				CLASS_MEMBER_FIELD(__vwsn_precompile_7)
				CLASS_MEMBER_FIELD(__vwsn_precompile_8)
				CLASS_MEMBER_FIELD(__vwsn_precompile_9)
				CLASS_MEMBER_FIELD(ViewModel)
				CLASS_MEMBER_FIELD(commandGlobalShow)
				CLASS_MEMBER_FIELD(programControl)
				CLASS_MEMBER_FIELD(self)
				CLASS_MEMBER_FIELD(tableMain)
				CLASS_MEMBER_FIELD(textBoxInput)
			END_CLASS_MEMBER(::gacfred::MainWindowConstructor)

			BEGIN_CLASS_MEMBER(::gacfred::TransparentButtonTemplate)
				CLASS_MEMBER_BASE(::vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_BASE(::gacfred::TransparentButtonTemplateConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::gacfred::TransparentButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(::gacfred::TransparentButtonTemplate)

			BEGIN_CLASS_MEMBER(::gacfred::TransparentButtonTemplateConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::gacfred::TransparentButtonTemplateConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_gacfred_TransparentButtonTemplate_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				CLASS_MEMBER_FIELD(self)
			END_CLASS_MEMBER(::gacfred::TransparentButtonTemplateConstructor)

			BEGIN_CLASS_MEMBER(::gacfred::VScrollHandleTemplate)
				CLASS_MEMBER_BASE(::vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_BASE(::gacfred::VScrollHandleTemplateConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::gacfred::VScrollHandleTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(::gacfred::VScrollHandleTemplate)

			BEGIN_CLASS_MEMBER(::gacfred::VScrollHandleTemplateConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::gacfred::VScrollHandleTemplateConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_gacfred_VScrollHandleTemplate_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(self)
			END_CLASS_MEMBER(::gacfred::VScrollHandleTemplateConstructor)

			BEGIN_CLASS_MEMBER(::gacfred::VScrollTemplate)
				CLASS_MEMBER_BASE(::vl::presentation::templates::GuiScrollTemplate)
				CLASS_MEMBER_BASE(::gacfred::VScrollTemplateConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::gacfred::VScrollTemplate*(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_instance_ctor_, NO_PARAMETER)
			END_CLASS_MEMBER(::gacfred::VScrollTemplate)

			BEGIN_CLASS_MEMBER(::gacfred::VScrollTemplateConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::gacfred::VScrollTemplateConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_gacfred_VScrollTemplate_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(behavior)
				CLASS_MEMBER_FIELD(handle)
				CLASS_MEMBER_FIELD(handleContainer)
				CLASS_MEMBER_FIELD(self)
			END_CLASS_MEMBER(::gacfred::VScrollTemplateConstructor)

			BEGIN_CLASS_MEMBER(::gacfred::WindowTemplate)
				CLASS_MEMBER_BASE(::vl::presentation::templates::GuiWindowTemplate)
				CLASS_MEMBER_BASE(::gacfred::WindowTemplateConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::gacfred::WindowTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(::gacfred::WindowTemplate)

			BEGIN_CLASS_MEMBER(::gacfred::WindowTemplateConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::gacfred::WindowTemplateConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_gacfred_WindowTemplate_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(self)
			END_CLASS_MEMBER(::gacfred::WindowTemplateConstructor)

#undef _
			class GacfredTypeLoader : public Object, public ITypeLoader
			{
			public:
				void Load(ITypeManager* manager)
				{
					ADD_TYPE_INFO(::gacfred::Clipboard)
					ADD_TYPE_INFO(::gacfred::ClipboardConstructor)
					ADD_TYPE_INFO(::gacfred::CopyItemTemplate)
					ADD_TYPE_INFO(::gacfred::CopyItemTemplateConstructor)
					ADD_TYPE_INFO(::gacfred::CopyType)
					ADD_TYPE_INFO(::gacfred::DocumentLabelTemplate)
					ADD_TYPE_INFO(::gacfred::DocumentLabelTemplateConstructor)
					ADD_TYPE_INFO(::gacfred::IClipboardViewModel)
					ADD_TYPE_INFO(::gacfred::ICopy)
					ADD_TYPE_INFO(::gacfred::IMainWindowViewModel)
					ADD_TYPE_INFO(::gacfred::IProgramViewModel)
					ADD_TYPE_INFO(::gacfred::ItemBackgroundTemplate)
					ADD_TYPE_INFO(::gacfred::ItemBackgroundTemplateConstructor)
					ADD_TYPE_INFO(::gacfred::ListViewTemplate)
					ADD_TYPE_INFO(::gacfred::ListViewTemplateConstructor)
					ADD_TYPE_INFO(::gacfred::MainWindow)
					ADD_TYPE_INFO(::gacfred::MainWindowConstructor)
					ADD_TYPE_INFO(::gacfred::TransparentButtonTemplate)
					ADD_TYPE_INFO(::gacfred::TransparentButtonTemplateConstructor)
					ADD_TYPE_INFO(::gacfred::VScrollHandleTemplate)
					ADD_TYPE_INFO(::gacfred::VScrollHandleTemplateConstructor)
					ADD_TYPE_INFO(::gacfred::VScrollTemplate)
					ADD_TYPE_INFO(::gacfred::VScrollTemplateConstructor)
					ADD_TYPE_INFO(::gacfred::WindowTemplate)
					ADD_TYPE_INFO(::gacfred::WindowTemplateConstructor)
				}

				void Unload(ITypeManager* manager)
				{
				}
			};
#endif
#endif

			bool LoadGacfredTypes()
			{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
				if (auto manager = GetGlobalTypeManager())
				{
					return manager->AddTypeLoader(Ptr(new GacfredTypeLoader));
				}
#endif
				return false;
			}
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
