/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_GACFREDREFLECTION
#define VCZH_WORKFLOW_COMPILER_GENERATED_GACFREDREFLECTION

#include "Gacfred.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			DECL_TYPE_INFO(::gacfred::Clipboard)
			DECL_TYPE_INFO(::gacfred::ClipboardConstructor)
			DECL_TYPE_INFO(::gacfred::CopyItemTemplate)
			DECL_TYPE_INFO(::gacfred::CopyItemTemplateConstructor)
			DECL_TYPE_INFO(::gacfred::CopyType)
			DECL_TYPE_INFO(::gacfred::DocumentLabelTemplate)
			DECL_TYPE_INFO(::gacfred::DocumentLabelTemplateConstructor)
			DECL_TYPE_INFO(::gacfred::IClipboardViewModel)
			DECL_TYPE_INFO(::gacfred::ICopy)
			DECL_TYPE_INFO(::gacfred::IMainWindowViewModel)
			DECL_TYPE_INFO(::gacfred::IProgramViewModel)
			DECL_TYPE_INFO(::gacfred::ItemBackgroundTemplate)
			DECL_TYPE_INFO(::gacfred::ItemBackgroundTemplateConstructor)
			DECL_TYPE_INFO(::gacfred::ListViewTemplate)
			DECL_TYPE_INFO(::gacfred::ListViewTemplateConstructor)
			DECL_TYPE_INFO(::gacfred::MainWindow)
			DECL_TYPE_INFO(::gacfred::MainWindowConstructor)
			DECL_TYPE_INFO(::gacfred::TransparentButtonTemplate)
			DECL_TYPE_INFO(::gacfred::TransparentButtonTemplateConstructor)
			DECL_TYPE_INFO(::gacfred::VScrollHandleTemplate)
			DECL_TYPE_INFO(::gacfred::VScrollHandleTemplateConstructor)
			DECL_TYPE_INFO(::gacfred::VScrollTemplate)
			DECL_TYPE_INFO(::gacfred::VScrollTemplateConstructor)
			DECL_TYPE_INFO(::gacfred::WindowTemplate)
			DECL_TYPE_INFO(::gacfred::WindowTemplateConstructor)

#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA

			BEGIN_INTERFACE_PROXY_NOPARENT_SHAREDPTR(::gacfred::ICopy)
				::vl::WString GetContent() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GetContent);
				}
				::vl::vint64_t GetCtime() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GetCtime);
				}
				::vl::WString GetIdx() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GetIdx);
				}
				::vl::Ptr<::vl::presentation::DocumentModel> GetRichContent(bool full) override
				{
					INVOKEGET_INTERFACE_PROXY(GetRichContent, full);
				}
				bool GetSeparatorVisible() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GetSeparatorVisible);
				}
				::vl::WString GetShowtime() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GetShowtime);
				}
				::gacfred::CopyType GetType() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GetType);
				}
				void SetContent(const ::vl::WString& __vwsn_value_) override
				{
					INVOKE_INTERFACE_PROXY(SetContent, __vwsn_value_);
				}
				void SetCtime(::vl::vint64_t __vwsn_value_) override
				{
					INVOKE_INTERFACE_PROXY(SetCtime, __vwsn_value_);
				}
				void SetIdx(const ::vl::WString& __vwsn_value_) override
				{
					INVOKE_INTERFACE_PROXY(SetIdx, __vwsn_value_);
				}
				void SetSeparatorVisible(bool __vwsn_value_) override
				{
					INVOKE_INTERFACE_PROXY(SetSeparatorVisible, __vwsn_value_);
				}
				void SetType(::gacfred::CopyType __vwsn_value_) override
				{
					INVOKE_INTERFACE_PROXY(SetType, __vwsn_value_);
				}
			END_INTERFACE_PROXY(::gacfred::ICopy)

			BEGIN_INTERFACE_PROXY_NOPARENT_SHAREDPTR(::gacfred::IMainWindowViewModel)
				void Copy() override
				{
					INVOKE_INTERFACE_PROXY_NOPARAMS(Copy);
				}
				::vl::WString GetProgram() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GetProgram);
				}
				::vl::Ptr<::gacfred::IProgramViewModel> GetProgramViewModel() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GetProgramViewModel);
				}
				::vl::WString GetSearch() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GetSearch);
				}
				void HandleKeyDown(::vl::presentation::compositions::GuiKeyEventArgs* arguments) override
				{
					INVOKE_INTERFACE_PROXY(HandleKeyDown, arguments);
				}
				void ResetSearch() override
				{
					INVOKE_INTERFACE_PROXY_NOPARAMS(ResetSearch);
				}
				void SetProgram(const ::vl::WString& __vwsn_value_) override
				{
					INVOKE_INTERFACE_PROXY(SetProgram, __vwsn_value_);
				}
				void SetProgramViewModel(::vl::Ptr<::gacfred::IProgramViewModel> __vwsn_value_) override
				{
					INVOKE_INTERFACE_PROXY(SetProgramViewModel, __vwsn_value_);
				}
				void SetSearch(const ::vl::WString& __vwsn_value_) override
				{
					INVOKE_INTERFACE_PROXY(SetSearch, __vwsn_value_);
				}
			END_INTERFACE_PROXY(::gacfred::IMainWindowViewModel)

			BEGIN_INTERFACE_PROXY_NOPARENT_SHAREDPTR(::gacfred::IProgramViewModel)
				::vl::WString GetSearch() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GetSearch);
				}
				bool HandleKeyDown(::vl::presentation::compositions::GuiKeyEventArgs* arguments) override
				{
					INVOKEGET_INTERFACE_PROXY(HandleKeyDown, arguments);
				}
				void SetSearch(const ::vl::WString& __vwsn_value_) override
				{
					INVOKE_INTERFACE_PROXY(SetSearch, __vwsn_value_);
				}
			END_INTERFACE_PROXY(::gacfred::IProgramViewModel)

			BEGIN_INTERFACE_PROXY_SHAREDPTR(::gacfred::IClipboardViewModel, ::gacfred::IProgramViewModel)
				void AddCopy(::vl::Ptr<::gacfred::ICopy> copy) override
				{
					INVOKE_INTERFACE_PROXY(AddCopy, copy);
				}
				::vl::Ptr<::vl::reflection::description::IValueObservableList> GetCopies() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GetCopies);
				}
				::vl::Ptr<::gacfred::ICopy> GetCopy(::vl::vint64_t idx) override
				{
					INVOKEGET_INTERFACE_PROXY(GetCopy, idx);
				}
				::gacfred::CopyType GetShowType() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GetShowType);
				}
				void SetShowType(::gacfred::CopyType __vwsn_value_) override
				{
					INVOKE_INTERFACE_PROXY(SetShowType, __vwsn_value_);
				}
			END_INTERFACE_PROXY(::gacfred::IClipboardViewModel)
#endif
#endif

			extern bool LoadGacfredTypes();
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
