/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_MAINWINDOW
#define VCZH_WORKFLOW_COMPILER_GENERATED_MAINWINDOW

#include "GacfredPartialClasses.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace gacfred
{
	class MainWindow : public ::vl::presentation::controls::GuiWindow, public ::gacfred::MainWindowConstructor, public ::vl::reflection::Description<MainWindow>
	{
		friend class ::gacfred::MainWindowConstructor;
		friend class ::vl_workflow_global::__vwsnc1_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc2_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc3_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc4_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc5_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc6_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc7_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc8_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc9_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend struct ::vl_workflow_global::__vwsnf10_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf11_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf12_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf13_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf14_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize__;
		friend struct ::vl_workflow_global::__vwsnf15_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf16_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf17_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf18_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf19_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf1_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf20_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf2_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf3_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf4_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize__;
		friend struct ::vl_workflow_global::__vwsnf5_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf6_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf7_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf8_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf9_Gacfred_gacfred_MainWindowConstructor___vwsn_gacfred_MainWindow_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<MainWindow>;
#endif
	public:
		::vl::Ptr<::gacfred::IMainWindowViewModel> __vwsn_parameter_ViewModel;
		::vl::Ptr<::gacfred::IMainWindowViewModel> GetViewModel();
		MainWindow(::vl::Ptr<::gacfred::IMainWindowViewModel> __vwsn_ctor_parameter_ViewModel);
		void __vwsn_instance_ctor_();
		~MainWindow();
	};

}
#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
// UNUSED_USER_CONTENT:
//	/* USER_CONTENT_BEGIN(custom members of ::gacfred::MainWindow) */
//	/* USER_CONTENT_END() */
